services:
  attu:
    image: zilliz/attu:v2.6.5
    container_name: james-attu
    ports:
      - "18002:3000"
    environment:
      MILVUS_URL: james-milvus:19530
    networks:
      - milvus_default
    restart: unless-stopped

networks:
  milvus_default:
    external: true
